# Generated by Django 5.2.16 on 2026-07-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descripition', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('trailer', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('release_year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.category')),
            ],
        ),
    ]
