# Generated by Django 5.2.16 on 2026-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_descripition_movie_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='trailer',
            new_name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='maturity_rating',
            field=models.CharField(default='13+', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='inception'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.collection'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
