# Generated by Django 5.2.16 on 2026-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='tv_posters/')),
                ('banner', models.ImageField(upload_to='tv_banners/')),
                ('trailer_url', models.URLField(blank=True)),
                ('release_year', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('language', models.CharField(default='English', max_length=50)),
                ('maturity_rating', models.CharField(default='13+', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='tv_shows', to='movies.collection')),
                ('genres', models.ManyToManyField(related_name='tv_shows', to='movies.genre')),
            ],
        ),
    ]
