# Generated by Django 5.2.16 on 2026-10-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_tvshow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='movies.movie')),
                ('tv_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='movies.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('tv_show__isnull', True)), models.Q(('movie__isnull', True), ('tv_show__isnull', False)), _connector='OR'), name='watchlist_exactly_one_content'), models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_watchlist'), models.UniqueConstraint(fields=('user', 'tv_show'), name='unique_user_tv_show_watchlist')],
            },
        ),
    ]
